env = Environment()

env.Append(CPPPATH=[Dir("#").abspath])

lib_sources = Split("""
            oclBuffer.cpp
            oclCommon.cpp
            oclContext.cpp
            oclDevice.cpp
            oclImage2D.cpp
            oclImage3D.cpp
            oclKernel.cpp
            oclMem.cpp
            oclObject.cpp
            oclProgram.cpp
            image/oclBloom.cpp
            image/oclBilateralGrid.cpp
            image/oclToneMapping.cpp
            image/oclAmbientOcclusion.cpp
            geom/oclBvhTrimesh.cpp
            color/oclColor.cpp
            color/oclQuantize.cpp
            phys/oclFluid3D.cpp
            phys/oclFluid3Dnext.cpp
            filter/oclTangent.cpp
            filter/oclRecursiveGaussian.cpp
            filter/oclSobel.cpp
            filter/oclConvolute.cpp
            filter/oclBilateralGrid.cpp
            filter/oclBilinearPyramid.cpp
            filter/oclBilateral.cpp
            math/oclVector.cpp
            sort/oclRadixSort.cpp
            util/oclMemory.cpp
""")

lib_objects = env.Object(source = lib_sources)

test_sources = Split("""
            TEST/console.cpp
            TEST/main.cpp
""")

env.Append(CPPPATH=[Dir("#/TEST").abspath])
test_objects = env.Object(source = test_sources)
